services:
  pgdatabase:
    image: postgres:13
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
      - ./database_backup:/dbbackup:rw
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: taxi_rides_all
    ports:
      - 5432:5432
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin:rw
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - pgdatabase
    networks:
      - pg-network

  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
    depends_on:
      - pgdatabase
    networks:
      - pg-network

networks:
  pg-network:

